name: Build scripts

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run dist
        cd ./fscd-src
        npm install
        npm run dist

    - name: Copy resources
      run: |
        cp -r data script/dist
        cp -r fs-context script/dist
        cp -r img script/dist
        cp -r style script/dist
        cp -r ext-maker script/dist

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: script/dist
        target-folder: .

    - name: Remove dist
      run: |
        rm -rf script/dist